import { Item, Category } from './types'

export const items: Item[] = [
  {
    "id": 1,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard",
    "color": "Black",
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 189,
    "description": "Riding hoodie not technical enough? Ski jacket too cumbersome? Yep, we get it, don’t worry. That’s why we designed the Blizzard. It feels like a riding hood, and performs like a full-blooded snow jacket. Awesome waterproofing and all the features you need for all-mountain hijinks, the Blizzard is a no-fuss, minimalist choice ideal for spring slush sessions or winter resort cruising. If comfort and performance are the name of the game, then the Blizzard is here to play.",
    "url": ["https://www.dopesnow.com/images/H1295_01_bQuNs3v.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1295_07_I8xb1ut.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1295_08_C6bSt5o.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 2,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Akin",
    "color": "Grey Camo",
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 259,
    "description": "The Akin is everything you ever wanted in a jacket, and a whole lot more. We took inspiration from old school utility jackets and decked this one out with seven outer pockets. Never worry again with this awesome design. Just zip up, load up, and head into the great unknown. Highly waterproof and insulated enough to tackle the harshest weather, the Akin is an easy park cruiser, and a big mountain bruiser. This is where we’d drop the mic, if we had one.",
    "url": ["https://www.dopesnow.com/images/H1288_01_1YlpPDz.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1288_07_4IdDDSi.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1288_08_90FBqHP.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 3,
    "categoryId": 1,
    "brand": "Dope",
    "name": "JT Legacy",
    "color": "JT Cobalt Blue/Navy Blue",
    "type": "Ski Jacket",
    "gender": "Men",
    "price": 219,
    "description": "The Limited Edition JT Legacy Pull Over is the product of our newest collaboration with ski wizard Jesper Tjäder. Made with relaxed sessions in mind, the Legacy is a pull-on-and-go style jacket that'll keep the snow off your back, and the other riders on their toes. When you don't need fancy zips or any of that other bulky snow-jacket stuff, the Legacy is perfect. It's new to the lineup this year, and is sure to leave a Legacy.",
    "url": ["https://www.dopesnow.com/images/H1640_01_SuL9BvP.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1640_06_JtnwG65.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1640_09_6VFrTRA.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 4,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Yeti",
    "color": "Peak Black",
    "type": "Ski Jacket",
    "gender": "Men",
    "price": 169,
    "description": "The Yeti is a mythical, elusive, mysterious beast... but there is one thing we know about it — that it's the best dang riding hoodie in the mountains! If you're looking for a reliable, cosy, comfy, and gosh-darn steezy softshell to take from the park to the pow, then hunt yourself down one of these and embrace the monster within. With lots of slick touches to make your day at the resort legendary, the Yeti is the only choice for your next snowy adventure.",
    "url": ["https://www.dopesnow.com/images/H1511_02_gyu7cEG.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1511_03_4iJdm3b.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1511_04_YhDCgLC.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 5,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept",
    "color": "Blue Steel",
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 219,
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1277_01_gOpgCIq.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1277_05_XlkzRLO.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1277_06_Vv1xeU8.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 6,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept W",
    "color": "Faded Violet",
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 219,
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1316_01_KKiURru.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1316_07_3jUsJt1.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1316_08_SDGFH0y.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 7,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard W",
    "color": "Black",
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 189,
    "description": "Riding hoodie not technical enough? Ski jacket too cumbersome? Yep, we get it, don’t worry. That’s why we designed the Blizzard. It feels like a riding hood, and performs like a full-blooded snow jacket. Awesome waterproofing and all the features you need for all-mountain hijinks, the Blizzard is a no-fuss, minimalist choice ideal for spring slush sessions or winter resort cruising. If comfort and performance are the name of the game, then the Blizzard is here to play.",
    "url": ["https://www.dopesnow.com/images/H1349_01_1Eyz1ew.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1349_07_p8Z8iIS.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1349_09_7X6lZWf.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 8,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Akin W",
    "color": "Soft Pink",
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 259,
    "description": "The Akin is everything you ever wanted in a jacket, and a whole lot more. We took inspiration from old school utility jackets and decked this one out with seven outer pockets. Never worry again with this awesome design. Just zip up, load up, and head into the great unknown. Highly waterproof and insulated enough to tackle the harshest weather, the Akin is an easy park cruiser, and a big mountain bruiser. This is where we’d drop the mic, if we had one.",
    "url": ["https://www.dopesnow.com/images/H1329_01_ee4zwLN.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1329_07_1MYK3I0.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1329_09_LM1yDpn.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 9,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Cyclone W",
    "color": "Walnut",
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 169,
    "description": "Sitting around pining for the nineties? For boxy cut jackets and really bad pop music? Well, us too. We sprinkled some retro flavour into our lineup with the Cyclone and blended modern softshell performance with a touch of throwback style to create... uh... this! Glorious, isn't it? It's got tech specs that'll make most ski jackets look like they're still running dial-up, and some awesome all-mountain design touches that make riding the whole resort a neon dream.",
    "url": ["https://www.dopesnow.com/images/H1377_01_h3KaglT.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1377_06_S2q7TU4.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1377_08_0C3BFdJ.jpg?w=725&dpr=1",
    ]  
  },
  {
    "id": 10,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept W",
    "color": "Cumulus",
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 219,
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1323_01_9eH0e6v.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1323_08_CXAFutt.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1323_05_qF5uzC9.jpg?w=725&dpr=1",
    ]  
  },
  {
    "id": 11,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic 2021",
    "color": "Rock",
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 159,
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://ridestore.imgix.net/catalog/product/F0620_01.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
            "https://ridestore.imgix.net/catalog/product/F0620_05.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
            "https://ridestore.imgix.net/catalog/product/F0620_03.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]
  },
  {
    "id": 12,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Notorious B.I.B",
    "color": "Khaki",
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 219,
    "description": "Add a little notoriety to your riding with the Notorious bib. It's a head turner and a piste burner, equipped with the latest tech to keep you warm and comfortable all day long. With super slick slouchy style that oozes steeze, and waterproofing that'd put a walrus to shame, the Notorious bib is a ride-everything, all-mountain slayer. And with an insanely comfortable relaxed fit and dropped crotch, unbeatable durability, and lots of storage, we wouldn't blame you if you never took it off. We know we haven't!",
    "url": ["https://www.dopesnow.com/images/H1424_01_TbpqwfB.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1424_05_KGwchnZ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1424_06_W8Szxeb.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 13,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Notorious B.I.B W",
    "color": "Black",
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 219,
    "description": "Add a little notoriety to your riding with the Notorious bib. It's a head turner and a piste burner, equipped with the latest tech to keep you warm and comfortable all day long. With super slick slouchy style that oozes steeze, and waterproofing that'd put a walrus to shame, the Notorious bib is a ride-everything, all-mountain slayer. And with an insanely comfortable relaxed fit and dropped crotch, unbeatable durability, and lots of storage, we wouldn't blame you if you never took it off. We know we haven't!",
    "url": ["https://www.dopesnow.com/images/H1466_01_Vwa5PA3.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1466_05_fPqbzEY.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1466_06_FucqWEw.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 14,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Con W",
    "color": "Black",
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 169,
    "description": "The Con pants perfectly blend form and function, and are a team favourite for good reason. These pants are special because they not only have that slimmer, thigh-hugging fit you’ve been craving, but are also super comfortable and provide total freedom of movement thanks to our improved 2-way stretch shell material. So, you still get that skinny-profile, but with no awkward pulling or tugging, which makes the Con the ultimate pair of slim-fit riding pants perfect for the whole mountain. You’re welcome.",
    "url": ["https://www.dopesnow.com/images/H1457_01_1r9nIkN.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1457_04_hyjgAn8.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1457_05_801Fep5.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 15,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Daily",
    "color": "Rose Black",
    "type": "T-shirt",
    "gender": "Men",
    "price": 29,
    "description": "The Daily T-Shirt from Dope is a super comfortable top with a new and improved design and fit for the 2021 season. Constructed from 100% BCI cotton, it has a mercerised finish for a smoother handfeel and better long term wear. Made from a slightly heavier cotton jersey, the Daily t-shirt is a firm favourite among the Dope crew, and you’ll only need to put it on to see why!",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9911_1.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9911_5.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9911_2.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 16,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Standard W",
    "color": "Peak White",
    "type": "T-shirt",
    "gender": "Women",
    "price": 39,
    "description": "The Standard T-Shirt is the perfect companion for every adventure. Made from a super soft Oekotext 100 certified 260gsm single jersey fabric with a 62% organic cotton/38% Tencel blend construction, it's ultra durable and high performance, too. We gave it our own signature Dope fit, and threw on our favourite designs to give it that little something extra. Whether it's a first layer for a day of lapping the resort, or you're hitting the beach at the height of summer, the Standard is the perfect choice for every season. Made in Lithuania.",
    "url": ["https://www.dopesnow.com/images/H1493_03_89af1A6.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1493_04_bzRAWg0.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1493_05_7cLCDtZ.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 17,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Standard W",
    "color": "Peak Black",
    "type": "T-shirt",
    "gender": "Women",
    "price": 39,
    "description": "The Standard T-Shirt is the perfect companion for every adventure. Made from a super soft Oekotext 100 certified 260gsm single jersey fabric with a 62% organic cotton/38% Tencel blend construction, it's ultra durable and high performance, too. We gave it our own signature Dope fit, and threw on our favourite designs to give it that little something extra. Whether it's a first layer for a day of lapping the resort, or you're hitting the beach at the height of summer, the Standard is the perfect choice for every season. Made in Lithuania.",
    "url": ["https://www.dopesnow.com/images/H1492_01_u0dyJM2.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1492_05_pfslvP7.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1492_04_MK0NWIc.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 18,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Daily",
    "color": "Rise Black",
    "type": "T-shirt",
    "gender": "Men",
    "price": 29,
    "description": "The Daily T-Shirt from Dope is a super comfortable top with a new and improved design and fit for the 2021 season. Constructed from 100% BCI cotton, it has a mercerised finish for a smoother handfeel and better long term wear. Made from a slightly heavier cotton jersey, the Daily t-shirt is a firm favourite among the Dope crew, and you’ll only need to put it on to see why!",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9907_1.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9907_5.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9907_6.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 19,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common W",
    "color": "Peak Black",
    "type": "Hoodie",
    "gender": "Women",
    "price": 89,
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1626_01_xSkEmAb.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1626_06_sU9VWIQ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1626_05_QzHSutF.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 20,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common W",
    "color": "Pine Black",
    "type": "Hoodie",
    "gender": "Women",
    "price": 89,
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1628_01_NrcxMmj.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1628_05_OUJaNEK.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1628_06_FBZt4ph.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 21,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Ozed",
    "color": "Black",
    "type": "Hoodie",
    "gender": "Men",
    "price": 74,
    "description": "The Ozed Hoodie from Dope is a comfy regular fitting hoodie with all the classic hoodie features you’d expect. We made the Ozed from a cosy 100% BCI cotton jersey with a unique mercerised outer to give it a smoother and softer handfeel, as well as better longevity. Inside, you get a brushed back terry fabric for that fleecy feel. So, if you’re looking to get a little Doper this summer, then look no further.",
    "url": ["https://ridestore.imgix.net/catalog/product/F0453_01_IuNmyt3.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/F0453_05_DaMRRRx.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/F0453_06_Ff4BEVU.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 22,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common",
    "color": "Peak Metal Blue",
    "type": "Hoodie",
    "gender": "Men",
    "price": 89,
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1614_01_BdFp1kf.jpg?w=60&blur=60",
          "https://www.dopesnow.com/images/H1614_05_GW1OdIr.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1614_06_dzWEH7H.jpg?w=725&dpr=1",
    ]      
  },
]

export const categories: Category[] = [
  {
    id: 1,
    name: "Jacket",
    url: 'https://www.dopesnow.com/images/H1295_01_bQuNs3v.jpg?w=725&dpr=1',
  },
  {
    id: 2,
    name: "Pants",
    url: 'https://www.dopesnow.com/images/H1642_01_EQzixQP.jpg?w=725&dpr=1',
  },
  {
    id: 3,
    name: "T-Shirts",
    url: 'https://ridestore.imgix.net/catalog/product//e/9/e9904_100.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max',
  },
  {
    id: 4,
    name: "Hoodies",
    url: 'https://www.dopesnow.com/images/H1609_01_pgKXpAs.jpg?w=725&dpr=1',
  }
]


