import { Item, Category, SortByTypes } from './types'

export const sizes: string[] = ['S', 'M', 'L', 'XL', 'XXL']
export const colors: string[] = ['black', 'grey', 'blue', 'violet', 'white', 'peach', 'pink', 'brown', 'khaki', 'sand',
  'red', 'green', 'orange']
export const sortBy: SortByTypes[] = [
  SortByTypes.priceAsc,
  SortByTypes.priceDesc,
  SortByTypes.rating
]

export const modelsName: string[] = ['Adept', 'Akin', 'Blizzard', 'Common', 'Con', 'Cyclone', 'Daily', 'Iconic', 'JT', 'Notorious', 'Ozed', 'Regular', 'Standard', 'Tigress', 'Yeti'];


export const items: Item[] = [
  {
    "id": 0,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard",
    "colorHTML": "Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 189,
    "rating": 4.69,
    "sizes": ['S', 'M', 'L', 'XL'], 
    "description": "Riding hoodie not technical enough? Ski jacket too cumbersome? Yep, we get it, don’t worry. That’s why we designed the Blizzard. It feels like a riding hood, and performs like a full-blooded snow jacket. Awesome waterproofing and all the features you need for all-mountain hijinks, the Blizzard is a no-fuss, minimalist choice ideal for spring slush sessions or winter resort cruising. If comfort and performance are the name of the game, then the Blizzard is here to play.",
    "url": ["https://www.dopesnow.com/images/H1295_01_bQuNs3v.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1295_07_I8xb1ut.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1295_08_C6bSt5o.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 1,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Akin",
    "colorHTML": "Grey Camo",
    "availableColors": ['grey'],
    "color": 'grey',
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 259,
    "rating": 4.30,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Akin is everything you ever wanted in a jacket, and a whole lot more. We took inspiration from old school utility jackets and decked this one out with seven outer pockets. Never worry again with this awesome design. Just zip up, load up, and head into the great unknown. Highly waterproof and insulated enough to tackle the harshest weather, the Akin is an easy park cruiser, and a big mountain bruiser. This is where we’d drop the mic, if we had one.",
    "url": ["https://www.dopesnow.com/images/H1288_01_1YlpPDz.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1288_07_4IdDDSi.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1288_08_90FBqHP.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 2,
    "categoryId": 1,
    "brand": "Dope",
    "name": "JT Legacy",
    "colorHTML": "JT Cobalt Blue/Navy Blue",
    "availableColors": ['blue'],
    "color": 'blue',
    "type": "Ski Jacket",
    "gender": "Men",
    "price": 219,
    "rating": 3.30,
    "sizes": ['S', 'M', 'L'], 
    "description": "The Limited Edition JT Legacy Pull Over is the product of our newest collaboration with ski wizard Jesper Tjäder. Made with relaxed sessions in mind, the Legacy is a pull-on-and-go style jacket that'll keep the snow off your back, and the other riders on their toes. When you don't need fancy zips or any of that other bulky snow-jacket stuff, the Legacy is perfect. It's new to the lineup this year, and is sure to leave a Legacy.",
    "url": ["https://www.dopesnow.com/images/H1640_01_SuL9BvP.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1640_06_JtnwG65.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1640_09_6VFrTRA.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 3,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Yeti",
    "colorHTML": "Peak Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Ski Jacket",
    "gender": "Men",
    "price": 169,
    "rating": 4.00,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Yeti is a mythical, elusive, mysterious beast... but there is one thing we know about it — that it's the best dang riding hoodie in the mountains! If you're looking for a reliable, cosy, comfy, and gosh-darn steezy softshell to take from the park to the pow, then hunt yourself down one of these and embrace the monster within. With lots of slick touches to make your day at the resort legendary, the Yeti is the only choice for your next snowy adventure.",
    "url": ["https://www.dopesnow.com/images/H1511_02_gyu7cEG.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1511_03_4iJdm3b.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1511_04_YhDCgLC.jpg?w=838&dpr=1",
    ]
  },
  {
    "id": 4,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept",
    "colorHTML": "Blue Steel",
    "availableColors": ['blue'],
    "color": 'blue',
    "type": "Snowboard Jacket",
    "gender": "Men",
    "price": 219,
    "rating": 4.63,
    "sizes": ['M', 'L'], 
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1277_01_gOpgCIq.jpg?w=838&dpr=1",
            "https://www.dopesnow.com/images/H1277_05_XlkzRLO.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1277_06_Vv1xeU8.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 5,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept W",
    "colorHTML": "Faded Violet",
    "availableColors": ['white', 'violet'],
    "color": 'violet',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 219,
    "rating": 3.63,
    "sizes": ['L', 'XL', 'XXL'], 
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1316_01_KKiURru.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1316_07_3jUsJt1.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1316_08_SDGFH0y.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 6,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard W",
    "colorHTML": "Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 189,
    "rating": 5.00,
    "sizes": ['S', 'M', 'L'], 
    "description": "Riding hoodie not technical enough? Ski jacket too cumbersome? Yep, we get it, don’t worry. That’s why we designed the Blizzard. It feels like a riding hood, and performs like a full-blooded snow jacket. Awesome waterproofing and all the features you need for all-mountain hijinks, the Blizzard is a no-fuss, minimalist choice ideal for spring slush sessions or winter resort cruising. If comfort and performance are the name of the game, then the Blizzard is here to play.",
    "url": ["https://www.dopesnow.com/images/H1349_01_1Eyz1ew.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1349_07_p8Z8iIS.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1349_09_7X6lZWf.jpg?w=725&dpr=1",
    ]
  },
  {
    "id": 7,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Akin W",
    "colorHTML": "Soft Pink",
    "availableColors": ['pink'],
    "color": 'pink',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 259,
    "rating": 4.00,
    "sizes": ['S', 'M', 'L'], 
    "description": "The Akin is everything you ever wanted in a jacket, and a whole lot more. We took inspiration from old school utility jackets and decked this one out with seven outer pockets. Never worry again with this awesome design. Just zip up, load up, and head into the great unknown. Highly waterproof and insulated enough to tackle the harshest weather, the Akin is an easy park cruiser, and a big mountain bruiser. This is where we’d drop the mic, if we had one.",
    "url": ["https://www.dopesnow.com/images/H1329_01_ee4zwLN.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1329_07_1MYK3I0.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1329_09_LM1yDpn.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 8,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Cyclone W",
    "colorHTML": "Walnut",
    "availableColors": ['brown'],
    "color": 'brown',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 169,
    "rating": 3.79,
    "sizes": ['S', 'M'], 
    "description": "Sitting around pining for the nineties? For boxy cut jackets and really bad pop music? Well, us too. We sprinkled some retro flavour into our lineup with the Cyclone and blended modern softshell performance with a touch of throwback style to create... uh... this! Glorious, isn't it? It's got tech specs that'll make most ski jackets look like they're still running dial-up, and some awesome all-mountain design touches that make riding the whole resort a neon dream.",
    "url": ["https://www.dopesnow.com/images/H1377_01_h3KaglT.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1377_06_S2q7TU4.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1377_08_0C3BFdJ.jpg?w=725&dpr=1",
    ]  
  },
  {
    "id": 9,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Adept W",
    "colorHTML": "Cumulus",
    "availableColors": ['white', 'violet'],
    "color": 'white',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 219,
    "rating": 4.79,
    "sizes": ['S'], 
    "description": "Simplicity redefined. The Adept is a reliable zip-through jacket with all the features you need for a long day on the slopes. Highly waterproof, durable, and designed with the whole mountain in mind, the Adept is a staple in the Dope Snow lineup, and for good reason too. So say goodbye to swapping coats on the fly and choose the last one you'll ever want to own. When it comes to checking all the boxes, this is it. One jacket that really can do it all.",
    "url": ["https://www.dopesnow.com/images/H1323_01_9eH0e6v.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1323_08_CXAFutt.jpg?w=725&dpr=1",
            "https://www.dopesnow.com/images/H1323_05_qF5uzC9.jpg?w=725&dpr=1",
    ]  
  },
  {
    "id": 10,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic 2021",
    "colorHTML": "Rock",
    "availableColors": ['white'],
    "color": 'white',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 159,
    "rating": 5.00,
    "sizes": ['M', 'L'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://ridestore.imgix.net/catalog/product/F0620_01.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
            "https://ridestore.imgix.net/catalog/product/F0620_05.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
            "https://ridestore.imgix.net/catalog/product/F0620_03.JPG?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]
  },
  {
    "id": 11,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Notorious B.I.B",
    "colorHTML": "Khaki",
    "availableColors": ['khaki'],
    "color": 'khaki',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 219,
    "rating": 3.35,
    "sizes": ['M'], 
    "description": "Add a little notoriety to your riding with the Notorious bib. It's a head turner and a piste burner, equipped with the latest tech to keep you warm and comfortable all day long. With super slick slouchy style that oozes steeze, and waterproofing that'd put a walrus to shame, the Notorious bib is a ride-everything, all-mountain slayer. And with an insanely comfortable relaxed fit and dropped crotch, unbeatable durability, and lots of storage, we wouldn't blame you if you never took it off. We know we haven't!",
    "url": ["https://www.dopesnow.com/images/H1424_01_TbpqwfB.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1424_05_KGwchnZ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1424_06_W8Szxeb.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 12,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Notorious B.I.B W",
    "colorHTML": "Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 219,
    "rating": 4.35,
    "sizes": ['S', 'M', 'L'], 
    "description": "Add a little notoriety to your riding with the Notorious bib. It's a head turner and a piste burner, equipped with the latest tech to keep you warm and comfortable all day long. With super slick slouchy style that oozes steeze, and waterproofing that'd put a walrus to shame, the Notorious bib is a ride-everything, all-mountain slayer. And with an insanely comfortable relaxed fit and dropped crotch, unbeatable durability, and lots of storage, we wouldn't blame you if you never took it off. We know we haven't!",
    "url": ["https://www.dopesnow.com/images/H1466_01_Vwa5PA3.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1466_05_fPqbzEY.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1466_06_FucqWEw.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 13,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Con W",
    "colorHTML": "Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 169,
    "rating": 4.75,
    "sizes": ['L', 'XL', 'XXL'], 
    "description": "The Con pants perfectly blend form and function, and are a team favourite for good reason. These pants are special because they not only have that slimmer, thigh-hugging fit you’ve been craving, but are also super comfortable and provide total freedom of movement thanks to our improved 2-way stretch shell material. So, you still get that skinny-profile, but with no awkward pulling or tugging, which makes the Con the ultimate pair of slim-fit riding pants perfect for the whole mountain. You’re welcome.",
    "url": ["https://www.dopesnow.com/images/H1457_01_1r9nIkN.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1457_04_hyjgAn8.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1457_05_801Fep5.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 14,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Daily",
    "colorHTML": "Rose Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "T-shirt",
    "gender": "Men",
    "price": 29,
    "rating": 4.85,
    "sizes": ['L', 'XL', 'XXL'], 
    "description": "The Daily T-Shirt from Dope is a super comfortable top with a new and improved design and fit for the 2021 season. Constructed from 100% BCI cotton, it has a mercerised finish for a smoother handfeel and better long term wear. Made from a slightly heavier cotton jersey, the Daily t-shirt is a firm favourite among the Dope crew, and you’ll only need to put it on to see why!",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9911_1.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9911_5.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9911_2.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 15,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Standard W",
    "colorHTML": "Peak White",
    "availableColors": ['black', 'white'],
    "color": 'white',
    "type": "T-shirt",
    "gender": "Women",
    "price": 39,
    "rating": 4.95,
    "sizes": ['S', 'L', 'XL'],
    "description": "The Standard T-Shirt is the perfect companion for every adventure. Made from a super soft Oekotext 100 certified 260gsm single jersey fabric with a 62% organic cotton/38% Tencel blend construction, it's ultra durable and high performance, too. We gave it our own signature Dope fit, and threw on our favourite designs to give it that little something extra. Whether it's a first layer for a day of lapping the resort, or you're hitting the beach at the height of summer, the Standard is the perfect choice for every season. Made in Lithuania.",
    "url": ["https://www.dopesnow.com/images/H1493_03_89af1A6.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1493_04_bzRAWg0.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1493_05_7cLCDtZ.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 16,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Standard W",
    "colorHTML": "Peak Black",
    "availableColors": ['black', 'white'],
    "color": 'black',
    "type": "T-shirt",
    "gender": "Women",
    "price": 39,
    "rating": 3.95,
    "sizes": ['S', 'M', 'XXL'], 
    "description": "The Standard T-Shirt is the perfect companion for every adventure. Made from a super soft Oekotext 100 certified 260gsm single jersey fabric with a 62% organic cotton/38% Tencel blend construction, it's ultra durable and high performance, too. We gave it our own signature Dope fit, and threw on our favourite designs to give it that little something extra. Whether it's a first layer for a day of lapping the resort, or you're hitting the beach at the height of summer, the Standard is the perfect choice for every season. Made in Lithuania.",
    "url": ["https://www.dopesnow.com/images/H1492_01_u0dyJM2.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1492_05_pfslvP7.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1492_04_MK0NWIc.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 17,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Daily",
    "colorHTML": "Rise Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "T-shirt",
    "gender": "Men",
    "price": 29,
    "rating": 4.35,
    "sizes": ['L', 'XL', 'XXL'], 
    "description": "The Daily T-Shirt from Dope is a super comfortable top with a new and improved design and fit for the 2021 season. Constructed from 100% BCI cotton, it has a mercerised finish for a smoother handfeel and better long term wear. Made from a slightly heavier cotton jersey, the Daily t-shirt is a firm favourite among the Dope crew, and you’ll only need to put it on to see why!",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9907_1.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9907_5.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9907_6.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 18,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common W",
    "colorHTML": "Peak Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Hoodie",
    "gender": "Women",
    "price": 89,
    "rating": 4.64,
    "sizes": ['L'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1626_01_xSkEmAb.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1626_06_sU9VWIQ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1626_05_QzHSutF.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 19,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common W",
    "colorHTML": "Pine Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Hoodie",
    "gender": "Women",
    "price": 89,
    "rating": 4.74,
    "sizes": ['L', 'XL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1628_01_NrcxMmj.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1628_05_OUJaNEK.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1628_06_FBZt4ph.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 20,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Ozed",
    "colorHTML": "Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Hoodie",
    "gender": "Men",
    "price": 74,
    "rating": 4.94,
    "sizes": ['S', 'M', 'L'], 
    "description": "The Ozed Hoodie from Dope is a comfy regular fitting hoodie with all the classic hoodie features you’d expect. We made the Ozed from a cosy 100% BCI cotton jersey with a unique mercerised outer to give it a smoother and softer handfeel, as well as better longevity. Inside, you get a brushed back terry fabric for that fleecy feel. So, if you’re looking to get a little Doper this summer, then look no further.",
    "url": ["https://ridestore.imgix.net/catalog/product/F0453_01_IuNmyt3.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/F0453_05_DaMRRRx.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/F0453_06_Ff4BEVU.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 21,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common",
    "colorHTML": "Peak Metal Blue",
    "availableColors": ['blue', 'sand', 'violet', 'red'],
    "color": 'blue',
    "type": "Hoodie",
    "gender": "Men",
    "price": 89,
    "rating": 5.00,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1614_02_y50MvxZ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1614_05_GW1OdIr.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1614_06_dzWEH7H.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 22,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common",
    "colorHTML": "Sand",
    "availableColors": ['blue', 'sand', 'violet', 'red'],
    "color": 'sand',
    "type": "Hoodie",
    "gender": "Men",
    "price": 89,
    "rating": 5.00,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1618_01_YgHBh2g.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1618_02_25SJnnZ.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1618_06_nFmHkeC.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 23,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common",
    "colorHTML": "Violet",
    "availableColors": ['blue', 'sand', 'violet', 'red'],
    "color": 'violet',
    "type": "Hoodie",
    "gender": "Men",
    "price": 89,
    "rating": 4.10,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1611_01_sFXdpAu.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1611_02_NLTYsNI.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1611_06_sVIdIYc.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 24,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Common",
    "colorHTML": "2X-Up Burgundy",
    "availableColors": ['blue', 'sand', 'violet', 'red'],
    "color": 'red',
    "type": "Hoodie",
    "gender": "Men",
    "price": 89,
    "rating": 3.64,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://www.dopesnow.com/images/H1610_01_Gc91ip4.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1610_04_1lj4Ck3.jpg?w=725&dpr=1",
          "https://www.dopesnow.com/images/H1610_03_CbDQ7nO.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 25,
    "categoryId": 4,
    "brand": "Dope",
    "name": "Regular",
    "colorHTML": "Rose Bleached Black",
    "availableColors": ['black'],
    "color": 'black',
    "type": "Hoodie",
    "gender": "Women",
    "price": 89,
    "rating": 4.56,
    "sizes": ['S', 'M', 'L', 'XL', 'XXL'], 
    "description": "The Common Hoodie is anything except run of the mill. Cosy, soft, and ready for anything, the Common hoodie is made from 100% organic cotton with a heavy-duty 400gsm Oekotex 100 certified terry loop fleece fabric for total warmth and all-season versatility. Finished off with plenty of slick Dope touches, this hoodie is the ultimate in both style and utility. Made in Portugal.",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9926_1.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9926_6.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://www.dopesnow.com/images/H1614_06_dzWEH7H.jpg?w=725&dpr=1",
    ]      
  },
  {
    "id": 26,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic W",
    "colorHTML": "Dots Phantom",
    "availableColors": ['black', 'green'],
    "color": 'black',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 169,
    "rating": 4.26,
    "sizes": ['S', 'M', 'L'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H1442_01_2squJ3M.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1442_03_Vthx8Tm.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1442_04_6fJqrUM.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 27,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic W",
    "colorHTML": "Olive Green",
    "availableColors": ['black', 'green'],
    "color": 'green',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 169,
    "rating": 4.66,
    "sizes": ['S', 'M', 'L'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H1434_01_hGd25n8.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1434_05_yrF0XWL.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1434_03_Y7ZKT5w.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 28,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Blizzard W",
    "colorHTML": "Peach",
    "availableColors": ['peach'],
    "color": 'peach',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 169,
    "rating": 4.76,
    "sizes": ['S', 'M', 'L'], 
    "description": "When you blend total comfort and performance, something special happens. The result? The Blizzard pants. We took everything we loved about snow pants, and everything we loved about sweatpants, and we smashed them together to make these baggy-fitting, soft-to-the-touch, ready-to-shred, 4-way stretching snow pants. They’ve got waterproofing to rival any fully fledged backcountry shell, and a cut that provides total freedom of movement. They’re stylish, durable, and ready for all the jibs, hucks, and sends you can muster. Sound good? We know, right.",
    "url": ["https://www.dopesnow.com/images/H1449_01_KWJmLkA.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1449_03_kObspHa.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1449_04_kvWvDiw.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 29,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic",
    "colorHTML": "Paint Orange",
    "availableColors": ['orange', 'khaki', 'blue', 'violet'],
    "color": 'orange',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 169,
    "rating": 4.75,
    "sizes": ['S', 'M', 'L', 'XL'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H1409_01_yigjiAy.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1409_05_uUelpdo.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1409_03_xPEtZU6.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 30,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic",
    "colorHTML": "Khaki",
    "availableColors": ['orange', 'khaki', 'blue', 'violet'],
    "color": 'khaki',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 169,
    "rating": 4.75,
    "sizes": ['S', 'M', 'L', 'XL'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H0862_01_3xWoiwO.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H0862_05_obuUW7d.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H0862_03_hh31a4r.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 31,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic",
    "colorHTML": "Blue Steel",
    "availableColors": ['orange', 'khaki', 'blue', 'violet'],
    "color": 'blue',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 159,
    "rating": 4.75,
    "sizes": ['S', 'M', 'L', 'XL'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H1404_01_BgI3Neg.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1404_05_uon6DJc.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1404_03_psfy8Xj.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 32,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Iconic",
    "colorHTML": "Faded Violet",
    "availableColors": ['orange', 'khaki', 'blue', 'violet'],
    "color": 'violet',
    "type": "Snowboard Pants",
    "gender": "Men",
    "price": 199,
    "rating": 4.93,
    "sizes": ['S', 'M', 'L'], 
    "description": "What is an Icon? Something that defines its sphere of influence. A true standout. A god among mortals. All of these things. More, even. And that's what we have created here. A defining pair of pants that rules the mountain with the kind of unattainable brilliance that all others aspire to. The Iconic are superbly waterproof, tailored to perfection with a relaxed and dropped-crotch fit, and so damn handsome that you can't quite look directly at them — kind of like the sun. And now, you too can share in their sheer, blinding magnificence, too, by owning your own pair.",
    "url": ["https://www.dopesnow.com/images/H1403_01_ErkveYd.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1403_05_sQzOGL6.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1403_03_QAyM4ah.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 33,
    "categoryId": 2,
    "brand": "Dope",
    "name": "JT Blizzard",
    "colorHTML": "Khaki Blue",
    "availableColors": ['khaki'],
    "color": 'khaki',
    "type": "Ski Pants",
    "gender": "Men",
    "price": 169,
    "rating": 4.28,
    "sizes": ['S', 'M', 'L'], 
    "description": "When comfort meets performance, and falls in love, the inevitable happens. The result? The Blizzard pants. We took everything we loved about snow pants, and everything we loved about sweatpants, and we smashed them together to make these baggy-fitting, soft-to-the-touch, ready-to-shred pants. They've got waterproofing to rival any fully fledged snow pant, and a cut that provides total freedom of movement. They're soft, durable, and ready for all the jibs, hucks, and sends you can muster. Sound good? We know, right.",
    "url": ["https://ridestore.imgix.net/catalog/product/H0231_01_T10rGED.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/H0231_03_mJyfJ2V.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/H0231_02_b0r2ggg.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 34,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Tigress W",
    "colorHTML": "Light Grey",
    "availableColors": ['grey', 'brown'],
    "color": 'grey',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 179,
    "rating": 4.28,
    "sizes": ['S', 'M', 'L'], 
    "description": "Skinny, stretchy snow pants. You might be sold already, just from those four words. But if not, allow us to sweeten the deal. We threw in a little spandex to give these pants some elasticity, and then cranked things up with some awesome design touches. They’ve got waterproofing for days, a 2-way stretch, as well as a snug fit with a bootcut hem, you know, just for a splash of retro flair. There are few pairs of pants out there that look like this, and even fewer that can handle everything mother earth serves up. From the jungle to the slopes, the tiger is on the hunt!",
    "url": ["https://www.dopesnow.com/images/H1474_01_0mcAZT9.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1474_04_vkXHb9O.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1474_05_8LeFx3T.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 35,
    "categoryId": 2,
    "brand": "Dope",
    "name": "Tigress W",
    "colorHTML": "Walnut",
    "availableColors": ['grey', 'brown'],
    "color": 'brown',
    "type": "Snowboard Pants",
    "gender": "Women",
    "price": 149,
    "rating": 4.45,
    "sizes": ['M', 'L'], 
    "description": "Skinny, stretchy snow pants. You might be sold already, just from those four words. But if not, allow us to sweeten the deal. We threw in a little spandex to give these pants some elasticity, and then cranked things up with some awesome design touches. They’ve got waterproofing for days, a 2-way stretch, as well as a snug fit with a bootcut hem, you know, just for a splash of retro flair. There are few pairs of pants out there that look like this, and even fewer that can handle everything mother earth serves up. From the jungle to the slopes, the tiger is on the hunt!",
    "url": ["https://www.dopesnow.com/images/H1475_01_T5nafTg.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1475_05_mdoxLrN.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1475_02_6e4mU0L.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 36,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Regular",
    "colorHTML": "Range Faded Grape",
    "availableColors": ['violet', 'green'],
    "color": 'violet',
    "type": "T-Shirt",
    "gender": "Women",
    "price": 29,
    "rating": 4.75,
    "sizes": ['M', 'L'], 
    "description": "The Regular T-Shirt from Dope is a slick new addition to the 2021 lineup, and features an all new fit and fabric construction to go with its unmistakable style. Made from super soft 100% cotton with a mercerised outer for a softer, smoother handfeel and better wear versus traditional cotton, it’s not only made to look good, but perform, too. And with the Better Cotton Initiative stamp of approval, you can feel great about wearing it, too.",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9961_1.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9961_6.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9961_4.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 37,
    "categoryId": 3,
    "brand": "Dope",
    "name": "Regular",
    "colorHTML": "Beak Faded Green",
    "availableColors": ['violet', 'green'],
    "color": 'green',
    "type": "T-Shirt",
    "gender": "Women",
    "price": 29,
    "rating": 4.75,
    "sizes": ['S', 'L'], 
    "description": "The Regular T-Shirt from Dope is a slick new addition to the 2021 lineup, and features an all new fit and fabric construction to go with its unmistakable style. Made from super soft 100% cotton with a mercerised outer for a softer, smoother handfeel and better wear versus traditional cotton, it’s not only made to look good, but perform, too. And with the Better Cotton Initiative stamp of approval, you can feel great about wearing it, too.",
    "url": ["https://ridestore.imgix.net/catalog/product/E/9/E9956_1.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9956_2.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
          "https://ridestore.imgix.net/catalog/product/E/9/E9956_6.jpg?w=488&q=80&dpr=1&usm=15&fm=avif&fit=max",
    ]      
  },
  {
    "id": 38,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard W Full Zip",
    "colorHTML": "Soft Green",
    "availableColors": ['green', 'violet', 'peach'],
    "color": 'green',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 209,
    "rating": 4.95,
    "sizes": ['S', 'L'], 
    "description": "Sleek, stylish, and ready for anything, the Blizzard Full Zip is a rider-favourite that blends comfort and performance, minus the frills. This zip-through combines a soft handfeel with the sort of technical specs you’d see on a big-ticket coat, resulting in a minimalist jacket ideal for spring sessions, or perfect for resort cruising in the winter. The Blizzard is a simplified all-mountain brawler that’ll stand up to pretty much anything mother nature serves up, and will no doubt be the jacket you reach for again and again this season thanks to its simple, comfy, and riding-forward design.",
    "url": ["https://www.dopesnow.com/images/H1344_01_XSjKcFn.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1344_09_mPivifb.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1344_05_Bqgh1FS.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 39,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard W Full Zip",
    "colorHTML": "Blot Violet",
    "availableColors": ['green', 'violet', 'peach'],
    "color": 'violet',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 209,
    "rating": 4.35,
    "sizes": ['S', 'M'], 
    "description": "Sleek, stylish, and ready for anything, the Blizzard Full Zip is a rider-favourite that blends comfort and performance, minus the frills. This zip-through combines a soft handfeel with the sort of technical specs you’d see on a big-ticket coat, resulting in a minimalist jacket ideal for spring sessions, or perfect for resort cruising in the winter. The Blizzard is a simplified all-mountain brawler that’ll stand up to pretty much anything mother nature serves up, and will no doubt be the jacket you reach for again and again this season thanks to its simple, comfy, and riding-forward design.",
    "url": ["https://www.dopesnow.com/images/H1346_01_1U7Q7xv.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1346_08_EYPJ1F5.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1346_09_etjBc9t.jpg?w=488&dpr=1",
    ]      
  },
  {
    "id": 40,
    "categoryId": 1,
    "brand": "Dope",
    "name": "Blizzard W Full Zip",
    "colorHTML": "Blot Peach",
    "availableColors": ['green', 'violet', 'peach'],
    "color": 'peach',
    "type": "Snowboard Jacket",
    "gender": "Women",
    "price": 209,
    "rating": 4.55,
    "sizes": ['S', 'XL'], 
    "description": "Sleek, stylish, and ready for anything, the Blizzard Full Zip is a rider-favourite that blends comfort and performance, minus the frills. This zip-through combines a soft handfeel with the sort of technical specs you’d see on a big-ticket coat, resulting in a minimalist jacket ideal for spring sessions, or perfect for resort cruising in the winter. The Blizzard is a simplified all-mountain brawler that’ll stand up to pretty much anything mother nature serves up, and will no doubt be the jacket you reach for again and again this season thanks to its simple, comfy, and riding-forward design.",
    "url": ["https://www.dopesnow.com/images/H1347_01_ZVqdtqm.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1347_08_ERekeIe.jpg?w=488&dpr=1",
          "https://www.dopesnow.com/images/H1347_03_rP7uHXh.jpg?w=488&dpr=1",
    ]      
  },
]

export const categories: Category[] = [
  {
    id: 1,
    name: "Jacket",
    url: 'https://www.dopesnow.com/images/H1295_01_bQuNs3v.jpg?w=725&dpr=1',
  },
  {
    id: 2,
    name: "Pants",
    url: 'https://www.dopesnow.com/images/H1642_01_EQzixQP.jpg?w=725&dpr=1',
  },
  {
    id: 3,
    name: "T-Shirts",
    url: 'https://ridestore.imgix.net/catalog/product//e/9/e9904_100.jpg?w=725&q=80&dpr=1&usm=15&fm=avif&fit=max',
  },
  {
    id: 4,
    name: "Hoodies",
    url: 'https://www.dopesnow.com/images/H1609_01_pgKXpAs.jpg?w=725&dpr=1',
  }
]


